# Generated by Django 4.2.5 on 2023-10-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_pwrd', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='prod_title',
            field=models.CharField(default='Product Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.CharField(default='Product Description', max_length=200),
        ),
    ]
