# Generated by Django 4.2.5 on 2023-10-02 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_customer_order_delete_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='shipping_status',
        ),
    ]
