# Generated by Django 4.2.5 on 2023-10-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_status_order_shipping_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_pwrd',
            new_name='pwrd',
        ),
    ]
