# Generated by Django 4.2.5 on 2023-10-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_order_quantity_product_is_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='on_sale',
        ),
    ]
