# Generated by Django 4.2.6 on 2023-10-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_is_sale_product_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='is_avaliable',
            field=models.BooleanField(default=True),
        ),
    ]
