# Generated by Django 4.2.6 on 2023-10-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_order_customer_remove_order_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
