# Generated by Django 4.2.6 on 2023-10-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
